apiVersion: monitoring.googleapis.com/v1alpha1
kind: PodMonitoring
metadata:
  name: checkly-prom-proxy
  labels:
    app.kubernetes.io/name: checkly-prom-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: checkly-prom-proxy
  endpoints:
  - port: metrics
    interval: 30s